sudo: false
language: php

php:
  - hhvm
  - 7.1
  - 7.0
  - 5.6
  - 5.5

env:
  - SLIM_VERSION=3.3.*
  - SLIM_VERSION=3.4.*
  - SLIM_VERSION=3.5.*
  - SLIM_VERSION=3.6.*
  - SLIM_VERSION=3.7.*
  - SLIM_VERSION=3.8.*

before_script:
  - composer self-update
  - travis_retry composer require "slim/slim:${SLIM_VERSION}"
  - mysql -e 'create database slim;'
  - php vendor/aimeos/aimeos-core/setup.php --config=src/aimeos-default.php unittest unittest

script:
  - vendor/bin/phpunit

after_success:
  - php vendor/bin/coveralls -c .coveralls.yml

matrix:
  fast_finish: true
